import { useState, useEffect, useMemo, useRef } from 'react'
import { Text, Button, Label, RelativeTime, Flash, Spinner } from '@primer/react'
import {
  IssueOpenedIcon,
  IssueClosedIcon,
  GitPullRequestIcon,
  GitMergeIcon,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  CommentIcon,
  LinkExternalIcon,
  XIcon,
  FileDiffIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  CheckCircleIcon,
  XCircleIcon,
  ClockIcon,
  GitCommitIcon,
  SkipIcon,
  SyncIcon,
  AlertIcon,
  CheckIcon,
} from '@primer/octicons-react'
import { marked } from 'marked'
import { IssueDetail, PRDetail, PRCheck, PRTimelineEvent, PRBranchStatus } from '@shared/types'

/** Wrapper around RelativeTime that guards against invalid dates */
function SafeRelativeTime({ date, ...props }: { date: Date; style?: React.CSSProperties }) {
  if (!date || isNaN(date.getTime())) return null
  return <RelativeTime date={date} {...props} />
}

// Configure marked for GitHub-flavored markdown
marked.setOptions({
  gfm: true,
  breaks: true,
})

/** Sanitize HTML by stripping script tags and event handlers */
function sanitizeHtml(html: string): string {
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
    .replace(/\bon\w+\s*=\s*["'][^"']*["']/gi, '')
    .replace(/\bon\w+\s*=\s*[^\s>]*/gi, '')
    .replace(/javascript:/gi, '')
}

/** Render markdown to sanitized HTML; converts #N to in-app links */
function renderMarkdown(md: string, repo?: string): string {
  try {
    // Convert bare #N references to proper GitHub links before parsing
    let processed = md
    if (repo) {
      processed = md.replace(/(^|[^&\w[])#(\d+)\b/g, (_, prefix, num) =>
        `${prefix}[#${num}](https://github.com/${repo}/issues/${num})`
      )
    }
    const raw = marked.parse(processed)
    if (typeof raw === 'string') return sanitizeHtml(raw)
    return sanitizeHtml(String(processed))
  } catch {
    return sanitizeHtml(md)
  }
}

/** Truncate very long text and provide expand toggle */
function TruncatedMarkdown({ content, repo, maxLen = 8000 }: { content: string; repo?: string; maxLen?: number }) {
  const [expanded, setExpanded] = useState(false)
  const isTruncated = content.length > maxLen
  const display = !expanded && isTruncated ? content.slice(0, maxLen) + '\n\n…' : content
  const html = useMemo(() => renderMarkdown(display, repo), [display, repo])

  return (
    <div>
      <div
        className="markdown-body"
        dangerouslySetInnerHTML={{ __html: html }}
      />
      {isTruncated && (
        <Button
          size="small"
          variant="invisible"
          onClick={() => setExpanded(e => !e)}
          leadingVisual={expanded ? ChevronUpIcon : ChevronDownIcon}
          style={{ marginTop: 4 }}
        >
          {expanded ? 'Show less' : `Show full content (${(content.length / 1024).toFixed(0)} KB)`}
        </Button>
      )}
    </div>
  )
}

const INITIAL_COMMENT_COUNT = 20

/** Detect automation identity from "Generated by [Name](url)" pattern in text */
function detectAutomationIdentity(text: string): { name: string; runUrl: string } | null {
  if (!text) return null
  // Check for "Generated by [Name](url)" pattern
  const genMatch = text.match(/Generated by \[([^\]]+)\]\(([^)]+)\)/)
  if (genMatch) return { name: genMatch[1], runUrl: genMatch[2] }
  // Check for HTML comment: <!-- gh-aw-agentic-workflow: Name, ... run: url -->
  const commentMatch = text.match(/gh-aw-agentic-workflow:\s*([^,]+),.*?run:\s*(\S+)\s*-->/)
  if (commentMatch) return { name: commentMatch[1].trim(), runUrl: commentMatch[2].trim() }
  return null
}

/** Format author display — if it's a bot, try to detect the real automation */
function AuthorDisplay({ login, body, openExternal }: { login: string; body?: string; openExternal?: (url: string) => void }) {
  const isBot = login === 'github-actions' || login === 'app/github-actions' || login?.endsWith('[bot]')
  const identity = isBot && body ? detectAutomationIdentity(body) : null

  if (identity) {
    return (
      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
        <span>{login}</span>
        <span style={{ color: 'var(--fgColor-muted)' }}>(</span>
        <a
          href="#"
          className="automation-identity-link"
          onClick={(e) => { e.preventDefault(); openExternal?.(identity.runUrl) }}
          style={{ color: '#da70d6', textDecoration: 'none', fontWeight: 600 }}
        >
          {identity.name}
        </a>
        <span style={{ color: 'var(--fgColor-muted)' }}>)</span>
      </span>
    )
  }
  return <span>{login ?? 'unknown'}</span>
}

interface DetailPanelProps {
  type: 'issue' | 'pr'
  repo: string
  number: number
  writeMode: boolean
  onClose: () => void
}

export function DetailPanel({ type, repo, number, writeMode, onClose }: DetailPanelProps) {
  const [issueDetail, setIssueDetail] = useState<IssueDetail | null>(null)
  const [prDetail, setPrDetail] = useState<PRDetail | null>(null)
  const [prDiff, setPrDiff] = useState<string | null>(null)
  const [diffExpanded, setDiffExpanded] = useState(true)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [commentText, setCommentText] = useState('')
  const [actionStatus, setActionStatus] = useState<string | null>(null)
  const [visibleComments, setVisibleComments] = useState(INITIAL_COMMENT_COUNT)
  const [ciChecks, setCiChecks] = useState<PRCheck[]>([])
  const [timeline, setTimeline] = useState<PRTimelineEvent[]>([])
  const [closing, setClosing] = useState(false)
  const [branchStatus, setBranchStatus] = useState<PRBranchStatus | null>(null)
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const [refreshKey, setRefreshKey] = useState(0)

  // Close on Escape key
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [onClose])

  useEffect(() => {
    setLoading(true)
    setError(null)
    setIssueDetail(null)
    setPrDetail(null)
    setPrDiff(null)
    setVisibleComments(INITIAL_COMMENT_COUNT)
    setBranchStatus(null)

    const load = async () => {
      try {
        if (type === 'issue') {
          const detail = await window.repoAssist.getIssueDetail(repo, number)
          setIssueDetail(detail)
        } else {
          const [detail, diff, tl] = await Promise.all([
            window.repoAssist.getPRDetail(repo, number),
            window.repoAssist.getPRDiff(repo, number),
            window.repoAssist.getPRTimeline(repo, number),
          ])
          setPrDetail(detail)
          setPrDiff(diff)
          setTimeline(tl)
          if (detail?.statusCheckRollup) setCiChecks(detail.statusCheckRollup)
          // Fetch branch status asynchronously
          window.repoAssist.getPRBranchStatus(repo, number).then(status => {
            setBranchStatus(status)
          }).catch(() => {})
        }
      } catch (err) {
        setError(`Failed to load details: ${err}`)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [type, repo, number, refreshKey])

  // Poll CI checks while PR is displayed and checks are pending
  useEffect(() => {
    if (type !== 'pr') return
    const hasPending = ciChecks.some(c =>
      c.status === 'IN_PROGRESS' || c.status === 'QUEUED' || c.status === 'PENDING'
    )
    if (!hasPending && ciChecks.length > 0) {
      // All done, stop polling
      if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null }
      return
    }
    // Start polling every 15s
    if (!pollRef.current) {
      pollRef.current = setInterval(async () => {
        try {
          const checks = await window.repoAssist.getPRChecks(repo, number)
          setCiChecks(checks)
        } catch { /* ignore */ }
      }, 15000)
    }
    return () => {
      if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null }
    }
  }, [type, repo, number, ciChecks])

  const openInGitHub = () => {
    const ghPath = type === 'issue' ? 'issues' : 'pull'
    window.repoAssist.openExternal(`https://github.com/${repo}/${ghPath}/${number}`)
  }

  const handleAddComment = async () => {
    if (!commentText.trim()) return
    setActionStatus('Adding comment…')
    try {
      await window.repoAssist.addComment(repo, number, commentText)
      setCommentText('')
      setActionStatus(writeMode ? 'Comment added!' : 'Comment logged (dry-run, read-only mode)')
      if (type === 'issue') {
        const detail = await window.repoAssist.getIssueDetail(repo, number)
        setIssueDetail(detail)
      } else {
        const detail = await window.repoAssist.getPRDetail(repo, number)
        setPrDetail(detail)
      }
    } catch (err) {
      setActionStatus(`Failed: ${err}`)
    }
    setTimeout(() => setActionStatus(null), 3000)
  }

  const handleMergePR = async () => {
    setActionStatus('Merging PR…')
    try {
      await window.repoAssist.mergePR(repo, number)
      setActionStatus(writeMode ? 'PR merged!' : 'Merge logged (dry-run, read-only mode)')
    } catch (err) {
      setActionStatus(`Failed: ${err}`)
    }
    setTimeout(() => setActionStatus(null), 3000)
  }

  const handleClosePR = async () => {
    setActionStatus('Closing PR…')
    try {
      await window.repoAssist.exec(`pr close ${number} -R ${repo}`)
      setActionStatus(writeMode ? 'PR closed!' : 'Close logged (dry-run, read-only mode)')
    } catch (err) {
      setActionStatus(`Failed: ${err}`)
    }
    setTimeout(() => setActionStatus(null), 3000)
  }

  const handleCloseIssue = async (reason: 'completed' | 'not_planned') => {
    const reasonLabel = reason === 'not_planned' ? 'not planned' : 'completed'
    setClosing(true)

    // Optimistic UI: update state and add a synthetic close event
    if (issueDetail) {
      setIssueDetail(prev => prev ? { ...prev, state: 'CLOSED' } : prev)
    }
    setActionStatus(`Closing issue as ${reasonLabel}…`)

    try {
      await window.repoAssist.closeIssue(repo, number, reason)

      if (!writeMode) {
        setActionStatus('Close logged (dry-run, read-only mode)')
        setClosing(false)
        setTimeout(() => setActionStatus(null), 3000)
        return
      }

      // Poll to confirm the issue is closed on GitHub (up to 10s)
      setActionStatus(`Issue closed as ${reasonLabel} — confirming…`)
      const deadline = Date.now() + 10000
      const poll = async (): Promise<boolean> => {
        while (Date.now() < deadline) {
          try {
            const fresh = await window.repoAssist.getIssueDetail(repo, number)
            if (fresh && (fresh.state === 'CLOSED' || fresh.state === 'closed')) {
              return true
            }
          } catch { /* ignore poll errors */ }
          await new Promise(r => setTimeout(r, 1500))
        }
        return false
      }
      const confirmed = await poll()
      if (confirmed) {
        setActionStatus(`Issue closed as ${reasonLabel} ✓`)
        setTimeout(() => onClose(), 800)
      } else {
        setActionStatus(`Issue closed as ${reasonLabel} (confirmation timed out)`)
        setTimeout(() => onClose(), 2000)
      }
    } catch (err) {
      // Revert optimistic state on failure
      if (issueDetail) {
        setIssueDetail(prev => prev ? { ...prev, state: 'OPEN' } : prev)
      }
      setClosing(false)
      setActionStatus(`Failed: ${err}`)
      setTimeout(() => setActionStatus(null), 3000)
    }
  }

  const handleMarkReady = async () => {
    setActionStatus('Marking as ready for review…')
    try {
      await window.repoAssist.markPRReady(repo, number)
      setActionStatus(writeMode ? 'Marked as ready!' : 'Mark ready logged (dry-run, read-only mode)')
      // Refresh detail and list data
      const detail = await window.repoAssist.getPRDetail(repo, number)
      setPrDetail(detail)
    } catch (err) {
      setActionStatus(`Failed: ${err}`)
    }
    setTimeout(() => setActionStatus(null), 3000)
  }

  const handleUpdateBranch = async () => {
    setActionStatus('Updating branch…')
    try {
      await window.repoAssist.updatePRBranch(repo, number)
      setActionStatus(writeMode ? 'Branch updated!' : 'Update logged (dry-run, read-only mode)')
      // Optimistic update
      setBranchStatus({ behindBy: 0, status: 'up_to_date' })
    } catch (err) {
      setActionStatus(`Failed: ${err}`)
    }
    setTimeout(() => setActionStatus(null), 3000)
  }

  const handleApprovePR = async () => {
    setActionStatus('Approving PR…')
    try {
      await window.repoAssist.approvePR(repo, number)
      setActionStatus(writeMode ? 'PR approved!' : 'Approval logged (dry-run, read-only mode)')
      // Refresh to pick up the new review
      const detail = await window.repoAssist.getPRDetail(repo, number)
      setPrDetail(detail)
    } catch (err) {
      setActionStatus(`Failed: ${err}`)
    }
    setTimeout(() => setActionStatus(null), 3000)
  }

  if (loading) {
    return (
      <div className="detail-panel fade-in">
        <div className="detail-header">
          <span />
          <div style={{ display: 'flex', gap: 4 }}>
            <Button size="small" variant="invisible" onClick={onClose} aria-label="Close detail">
              <XIcon size={16} />
            </Button>
          </div>
        </div>
        <div className="loading-center" style={{ height: 200 }}>
          <Spinner size="medium" />
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="detail-panel fade-in">
        <div className="detail-header">
          <span />
          <div style={{ display: 'flex', gap: 4 }}>
            <Button size="small" variant="invisible" onClick={() => setRefreshKey(k => k + 1)} aria-label="Refresh">
              <SyncIcon size={16} />
            </Button>
            <Button size="small" variant="invisible" onClick={onClose} aria-label="Close detail">
              <XIcon size={16} />
            </Button>
          </div>
        </div>
        <Flash variant="danger">{error}</Flash>
      </div>
    )
  }

  // Shared comment rendering
  const renderComments = (
    comments: { author: { login: string }; body: string; createdAt: string }[],
    label: string
  ) => {
    if (!Array.isArray(comments) || comments.length === 0) return null
    const shown = comments.slice(0, visibleComments)
    const remaining = comments.length - shown.length

    return (
      <div className="detail-comments">
        <h4 className="detail-section-title">
          <CommentIcon size={16} /> {comments.length} {label}
        </h4>
        {shown.map((c, i) => (
          <div key={i} className="detail-comment">
            <div className="detail-comment-header">
              <span className="comment-avatar">
                {(c.author?.login ?? '?')[0].toUpperCase()}
              </span>
              <Text weight="semibold" size="small">
                <AuthorDisplay
                  login={c.author?.login ?? 'unknown'}
                  body={c.body}
                  openExternal={window.repoAssist.openExternal}
                />
              </Text>
              <SafeRelativeTime date={new Date(c.createdAt)} />
            </div>
            <TruncatedMarkdown content={c.body || ''} repo={repo} maxLen={4000} />
          </div>
        ))}
        {remaining > 0 && (
          <Button
            size="small"
            variant="invisible"
            onClick={() => setVisibleComments(v => v + 20)}
            style={{ marginTop: 4 }}
          >
            Show {Math.min(remaining, 20)} more comments ({remaining} remaining)
          </Button>
        )}
      </div>
    )
  }

  // Issue detail view
  if (type === 'issue' && issueDetail) {
    return (
      <div className="detail-panel fade-in">
        <div className="detail-header">
          <div className="detail-title-row">
            {issueDetail.state === 'closed' || issueDetail.state === 'CLOSED'
              ? <IssueClosedIcon size={20} className="gh-icon-closed-issue" />
              : <IssueOpenedIcon size={20} className="gh-icon-open" />
            }
            <div>
              <h3 className="detail-title">#{issueDetail.number} {issueDetail.title}</h3>
              <div className="detail-meta">
                <Text size="small" style={{ color: 'var(--fgColor-muted)' }}>
                  by <AuthorDisplay
                    login={issueDetail.author?.login ?? 'unknown'}
                    body={issueDetail.body}
                    openExternal={window.repoAssist.openExternal}
                  />
                </Text>
                <SafeRelativeTime date={new Date(issueDetail.createdAt)} />
                {issueDetail.labels?.map(l => (
                  <Label key={l.name} size="small">{l.name}</Label>
                ))}
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 4 }}>
            <Button size="small" variant="invisible" onClick={() => setRefreshKey(k => k + 1)} aria-label="Refresh">
              <SyncIcon size={16} />
            </Button>
            <Button size="small" variant="invisible" onClick={onClose} aria-label="Close detail">
              <XIcon size={16} />
            </Button>
          </div>
        </div>

        {/* Body — rendered as markdown */}
        <div className="detail-body">
          {issueDetail.body ? (
            <TruncatedMarkdown content={issueDetail.body} repo={repo} />
          ) : (
            <Text size="small" style={{ color: 'var(--fgColor-muted)', fontStyle: 'italic' }}>No description provided.</Text>
          )}
        </div>

        {/* Comments — GitHub style */}
        {renderComments(issueDetail.comments, 'comments')}

        {/* Actions */}
        <div className="detail-actions">
          {issueDetail.state !== 'CLOSED' && issueDetail.state !== 'closed' && (
            <>
              <Button size="small" variant="primary" onClick={() => handleCloseIssue('completed')} disabled={closing}>
                {writeMode ? 'Close (completed)' : 'Close (completed, dry-run)'}
              </Button>
              <Button size="small" variant="danger" onClick={() => handleCloseIssue('not_planned')} disabled={closing}>
                {writeMode ? 'Close (not planned)' : 'Close (not planned, dry-run)'}
              </Button>
            </>
          )}
          <Button size="small" leadingVisual={LinkExternalIcon} onClick={openInGitHub}>
            Open in GitHub
          </Button>
        </div>

        {/* Add Comment */}
        <div className="detail-comment-form">
          <textarea
            className="detail-textarea"
            placeholder="Add a comment…"
            value={commentText}
            onChange={e => setCommentText(e.target.value)}
            rows={3}
          />
          <Button size="small" variant="primary" onClick={handleAddComment} disabled={!commentText.trim()}>
            Comment{!writeMode && ' (dry-run)'}
          </Button>
        </div>

        {actionStatus && <Flash variant="default" style={{ marginTop: 8 }}>{actionStatus}</Flash>}
      </div>
    )
  }

  // PR detail view
  if (type === 'pr' && prDetail) {
    const stateIcon = prDetail.isDraft
      ? <GitPullRequestDraftIcon size={20} className="gh-icon-draft" />
      : prDetail.state === 'MERGED'
        ? <GitMergeIcon size={20} className="gh-icon-merged" />
        : prDetail.state === 'CLOSED'
          ? <GitPullRequestClosedIcon size={20} className="gh-icon-closed" />
          : <GitPullRequestIcon size={20} className="gh-icon-open" />

    // Detect bot identity from PR body — used for automation badge in header
    const prAuthorIdentity = detectAutomationIdentity(prDetail.body || '')

    return (
      <div className="detail-panel fade-in">
        <div className="detail-header">
          <div className="detail-title-row">
            {stateIcon}
            <div>
              <h3 className="detail-title">#{prDetail.number} {prDetail.title}</h3>
              <div className="detail-meta">
                <Text size="small" style={{ color: 'var(--fgColor-muted)' }}>
                  by <AuthorDisplay
                    login={prDetail.author?.login ?? 'unknown'}
                    body={prDetail.body}
                    openExternal={window.repoAssist.openExternal}
                  />
                </Text>
                <Label size="small">{prDetail.headRefName}</Label>
                {prDetail.isDraft && <Label size="small" variant="secondary">Draft</Label>}
                {prAuthorIdentity && (
                  <a
                    href="#"
                    onClick={(e) => { e.preventDefault(); window.repoAssist.openExternal(prAuthorIdentity.runUrl) }}
                    style={{ textDecoration: 'none' }}
                  >
                    <Label size="small" variant="accent">⚡ {prAuthorIdentity.name}</Label>
                  </a>
                )}
                <SafeRelativeTime date={new Date(prDetail.createdAt)} />
                {prDetail.additions != null && (
                  <span className="diff-stat">
                    <span className="diff-add">+{prDetail.additions}</span>
                    <span className="diff-del">−{prDetail.deletions}</span>
                  </span>
                )}
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 4 }}>
            <Button size="small" variant="invisible" onClick={() => setRefreshKey(k => k + 1)} aria-label="Refresh">
              <SyncIcon size={16} />
            </Button>
            <Button size="small" variant="invisible" onClick={onClose} aria-label="Close detail">
              <XIcon size={16} />
            </Button>
          </div>
        </div>

        {/* Body — rendered as markdown */}
        <div className="detail-body">
          {prDetail.body ? (
            <TruncatedMarkdown content={prDetail.body} repo={repo} />
          ) : (
            <Text size="small" style={{ color: 'var(--fgColor-muted)', fontStyle: 'italic' }}>No description provided.</Text>
          )}
        </div>

        {/* Files changed — summary + diff */}
        {Array.isArray(prDetail.files) && prDetail.files.length > 0 && (
          <div className="detail-files">
            <h4 className="detail-section-title">
              <FileDiffIcon size={16} /> {prDetail.files.length} files changed
              <Button
                size="small"
                variant="invisible"
                onClick={() => setDiffExpanded(e => !e)}
                leadingVisual={diffExpanded ? ChevronUpIcon : ChevronDownIcon}
                style={{ marginLeft: 'auto' }}
              >
                {diffExpanded ? 'Hide diff' : 'Show diff'}
              </Button>
            </h4>
            <div className="detail-file-list">
              {prDetail.files.map(f => (
                <div key={f.path} className="detail-file-row">
                  <Text size="small" style={{ fontFamily: 'var(--fontFamily-mono)' }}>{f.path}</Text>
                  <span className="diff-stat">
                    <span className="diff-add">+{f.additions}</span>
                    <span className="diff-del">−{f.deletions}</span>
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Unified diff view */}
        {diffExpanded && prDiff && (
          <DiffView diff={prDiff} />
        )}

        {/* Timeline — commits, force pushes, events */}
        {timeline.length > 0 && (
          <TimelineView timeline={timeline} />
        )}

        {/* Reviews */}
        {Array.isArray(prDetail.reviews) && prDetail.reviews.length > 0 && (
          <div className="detail-comments">
            <h4 className="detail-section-title">Reviews</h4>
            {prDetail.reviews.map((r, i) => (
              <div key={i} className="detail-comment">
                <div className="detail-comment-header">
                  <span className="comment-avatar">
                    {(r.author?.login ?? '?')[0].toUpperCase()}
                  </span>
                  <Text weight="semibold" size="small">{r.author?.login ?? 'unknown'}</Text>
                  <Label size="small" variant={r.state === 'APPROVED' ? 'success' : r.state === 'CHANGES_REQUESTED' ? 'danger' : 'secondary'}>
                    {r.state}
                  </Label>
                  <SafeRelativeTime date={new Date(r.createdAt)} />
                </div>
                {r.body && <TruncatedMarkdown content={r.body} repo={repo} maxLen={4000} />}
              </div>
            ))}
          </div>
        )}

        {/* Comments */}
        {renderComments(prDetail.comments, 'comments')}

        {/* CI Status Checks */}
        {ciChecks.length > 0 && (
          <CIChecksPanel checks={ciChecks} openExternal={window.repoAssist.openExternal} />
        )}

        {/* Branch status — behind base */}
        {branchStatus?.status === 'behind' && (
          <Flash variant="warning" style={{ marginTop: 8, display: 'flex', alignItems: 'center', gap: 8 }}>
            <AlertIcon size={16} />
            <span>Branch is {branchStatus.behindBy} commit{branchStatus.behindBy !== 1 ? 's' : ''} behind {prDetail.headRefName ? 'the base branch' : 'base'}</span>
            <Button size="small" leadingVisual={SyncIcon} onClick={handleUpdateBranch} style={{ marginLeft: 'auto' }}>
              {writeMode ? 'Update branch' : 'Update branch (dry-run)'}
            </Button>
          </Flash>
        )}

        {/* Actions */}
        <div className="detail-actions">
          {prDetail.isDraft && (
            <Button size="small" variant="primary" onClick={handleMarkReady}>
              {writeMode ? 'Ready for review' : 'Ready for review (dry-run)'}
            </Button>
          )}
          {!prDetail.isDraft && prDetail.state !== 'MERGED' && prDetail.state !== 'CLOSED' && prDetail.reviewDecision !== 'APPROVED' && (
            <Button size="small" leadingVisual={CheckIcon} onClick={handleApprovePR}>
              {writeMode ? 'Approve PR' : 'Approve PR (dry-run)'}
            </Button>
          )}
          <Button size="small" variant="primary" onClick={handleMergePR} disabled={prDetail.isDraft}>
            {writeMode ? 'Merge PR' : 'Merge PR (dry-run)'}
          </Button>
          <Button size="small" variant="danger" onClick={handleClosePR}>
            {writeMode ? 'Close PR' : 'Close PR (dry-run)'}
          </Button>
          <Button size="small" leadingVisual={LinkExternalIcon} onClick={openInGitHub}>
            Open in GitHub
          </Button>
        </div>

        {/* Add Comment */}
        <div className="detail-comment-form">
          <textarea
            className="detail-textarea"
            placeholder="Add a comment…"
            value={commentText}
            onChange={e => setCommentText(e.target.value)}
            rows={3}
          />
          <Button size="small" variant="primary" onClick={handleAddComment} disabled={!commentText.trim()}>
            Comment{!writeMode && ' (dry-run)'}
          </Button>
        </div>

        {actionStatus && <Flash variant="default" style={{ marginTop: 8 }}>{actionStatus}</Flash>}
      </div>
    )
  }

  return null
}

/** CI Status Checks panel — shown at top of PR detail */
function CIChecksPanel({ checks, openExternal }: { checks: PRCheck[]; openExternal: (url: string) => void }) {
  const passed = checks.filter(c => c.conclusion === 'SUCCESS' || c.conclusion === 'NEUTRAL')
  const failed = checks.filter(c => c.conclusion === 'FAILURE' || c.conclusion === 'CANCELLED' || c.conclusion === 'TIMED_OUT')
  const pending = checks.filter(c => c.status === 'IN_PROGRESS' || c.status === 'QUEUED' || c.status === 'PENDING')
  const skipped = checks.filter(c => c.conclusion === 'SKIPPED')

  const hasFailed = failed.length > 0
  const hasPending = pending.length > 0

  const summaryIcon = hasFailed
    ? <XCircleIcon size={16} className="gh-icon-danger" />
    : hasPending
      ? <ClockIcon size={16} className="gh-icon-attention" />
      : <CheckCircleIcon size={16} className="gh-icon-success" />

  const summaryText = hasFailed
    ? `${failed.length} failing`
    : hasPending
      ? `${pending.length} pending`
      : `${passed.length} passing`

  const [expanded, setExpanded] = useState(hasFailed || hasPending)

  return (
    <div className="ci-checks-panel">
      <div className="ci-checks-summary" onClick={() => setExpanded(e => !e)} style={{ cursor: 'pointer' }}>
        {summaryIcon}
        <Text size="small" weight="semibold">
          {summaryText}
          {passed.length > 0 && (hasFailed || hasPending) && `, ${passed.length} passing`}
          {skipped.length > 0 && `, ${skipped.length} skipped`}
        </Text>
        {hasPending && <Spinner size="small" />}
        {expanded ? <ChevronUpIcon size={14} /> : <ChevronDownIcon size={14} />}
      </div>
      {expanded && (
        <div className="ci-checks-list">
          {[...failed, ...pending, ...passed].map((c, i) => {
            const icon = c.conclusion === 'SUCCESS' || c.conclusion === 'NEUTRAL'
              ? <CheckCircleIcon size={14} className="gh-icon-success" />
              : c.conclusion === 'FAILURE' || c.conclusion === 'CANCELLED' || c.conclusion === 'TIMED_OUT'
                ? <XCircleIcon size={14} className="gh-icon-danger" />
                : c.conclusion === 'SKIPPED'
                  ? <SkipIcon size={14} className="gh-icon-muted" />
                  : <ClockIcon size={14} className="gh-icon-attention" />
            return (
              <div key={i} className="ci-check-row">
                {icon}
                <Text size="small" style={{ flex: 1 }}>{c.name}</Text>
                {c.workflowName && (
                  <Text size="small" style={{ color: 'var(--fgColor-muted)' }}>{c.workflowName}</Text>
                )}
                {c.detailsUrl && (
                  <a
                    href="#"
                    onClick={(e) => { e.preventDefault(); openExternal(c.detailsUrl) }}
                    style={{ color: '#58a6ff', fontSize: 12 }}
                  >
                    Details
                  </a>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

/** PR Timeline — commits, force pushes, events */
function TimelineView({ timeline }: { timeline: PRTimelineEvent[] }) {
  const [expanded, setExpanded] = useState(false)
  // Only show committed, head_ref_force_pushed, ready_for_review, closed, merged, reopened, convert_to_draft
  const relevant = timeline.filter(e =>
    ['committed', 'head_ref_force_pushed', 'ready_for_review', 'closed', 'merged', 'reopened', 'convert_to_draft'].includes(e.event)
  )
  if (relevant.length === 0) return null

  const preview = relevant.slice(0, 5)
  const display = expanded ? relevant : preview

  return (
    <div className="detail-timeline">
      <h4 className="detail-section-title">
        <GitCommitIcon size={16} /> Timeline ({relevant.length} events)
        {relevant.length > 5 && (
          <Button
            size="small"
            variant="invisible"
            onClick={() => setExpanded(e => !e)}
            style={{ marginLeft: 'auto' }}
          >
            {expanded ? 'Show less' : `Show all ${relevant.length}`}
          </Button>
        )}
      </h4>
      <div className="timeline-list">
        {display.map((e, i) => (
          <TimelineEventRow key={i} event={e} />
        ))}
      </div>
    </div>
  )
}

function TimelineEventRow({ event }: { event: PRTimelineEvent }) {
  const { event: eventType, created_at, actor, message, sha } = event

  let icon: React.ReactNode
  let label: string
  let detail: string

  switch (eventType) {
    case 'committed':
      icon = <GitCommitIcon size={14} className="gh-icon-accent" />
      label = message ? message.split('\n')[0] : 'Commit'
      detail = sha ? sha.substring(0, 7) : ''
      break
    case 'head_ref_force_pushed':
      icon = <GitCommitIcon size={14} className="gh-icon-attention" />
      label = `${actor?.login ?? 'someone'} force-pushed`
      detail = ''
      break
    case 'ready_for_review':
      icon = <GitPullRequestIcon size={14} className="gh-icon-open" />
      label = `${actor?.login ?? 'someone'} marked as ready for review`
      detail = ''
      break
    case 'convert_to_draft':
      icon = <GitPullRequestDraftIcon size={14} className="gh-icon-draft" />
      label = `${actor?.login ?? 'someone'} converted to draft`
      detail = ''
      break
    case 'closed':
      icon = <GitPullRequestClosedIcon size={14} className="gh-icon-closed" />
      label = `${actor?.login ?? 'someone'} closed`
      detail = ''
      break
    case 'merged':
      icon = <GitMergeIcon size={14} className="gh-icon-merged" />
      label = `${actor?.login ?? 'someone'} merged`
      detail = ''
      break
    case 'reopened':
      icon = <GitPullRequestIcon size={14} className="gh-icon-open" />
      label = `${actor?.login ?? 'someone'} reopened`
      detail = ''
      break
    default:
      icon = <ClockIcon size={14} className="gh-icon-muted" />
      label = eventType
      detail = ''
  }

  return (
    <div className="timeline-event">
      {icon}
      <Text size="small" style={{ flex: 1 }}>{label}</Text>
      {detail && <Text size="small" style={{ color: 'var(--fgColor-muted)', fontFamily: 'var(--fontFamily-mono)' }}>{detail}</Text>}
      {created_at && <SafeRelativeTime date={new Date(created_at)} style={{ fontSize: 12 }} />}
    </div>
  )
}

/** Render unified diff with colored lines */
function DiffView({ diff }: { diff: string }) {
  const MAX_DIFF_LINES = 2000
  const lines = diff.split('\n')
  const truncated = lines.length > MAX_DIFF_LINES
  const displayLines = truncated ? lines.slice(0, MAX_DIFF_LINES) : lines

  return (
    <div className="diff-view">
      {displayLines.map((line, i) => {
        let className = 'diff-line'
        if (line.startsWith('+++') || line.startsWith('---')) {
          className += ' diff-line-header'
        } else if (line.startsWith('@@')) {
          className += ' diff-line-hunk'
        } else if (line.startsWith('+')) {
          className += ' diff-line-add'
        } else if (line.startsWith('-')) {
          className += ' diff-line-del'
        }
        return (
          <div key={i} className={className}>
            {line}
          </div>
        )
      })}
      {truncated && (
        <div className="diff-line diff-line-hunk" style={{ textAlign: 'center', padding: 8 }}>
          … diff truncated ({lines.length - MAX_DIFF_LINES} more lines)
        </div>
      )}
    </div>
  )
}
