import { describe, it, expect, vi, beforeEach } from 'vitest'
import { parseGhArgs, isAutomationActor, stripCodeFences, extractAutomationName, GhBridge } from './gh-bridge'

// === Pure function tests (no mocking needed) ===

describe('parseGhArgs', () => {
  it('splits simple command', () => {
    expect(parseGhArgs('issue list -R owner/repo')).toEqual(['issue', 'list', '-R', 'owner/repo'])
  })

  it('handles double-quoted strings', () => {
    expect(parseGhArgs('issue comment 1 --body "hello world"')).toEqual([
      'issue', 'comment', '1', '--body', 'hello world'
    ])
  })

  it('handles single-quoted strings', () => {
    expect(parseGhArgs("pr merge 1 --body 'some message'")).toEqual([
      'pr', 'merge', '1', '--body', 'some message'
    ])
  })

  it('handles multiple spaces between args', () => {
    expect(parseGhArgs('api  repos/owner/repo  --jq  .sha')).toEqual([
      'api', 'repos/owner/repo', '--jq', '.sha'
    ])
  })

  it('handles empty string', () => {
    expect(parseGhArgs('')).toEqual([])
  })

  it('handles complex API command', () => {
    expect(parseGhArgs('api repos/owner/repo/compare/main...feature --jq .behind_by')).toEqual([
      'api', 'repos/owner/repo/compare/main...feature', '--jq', '.behind_by'
    ])
  })
})

describe('isAutomationActor', () => {
  it('detects [bot] suffix', () => {
    expect(isAutomationActor('dependabot[bot]')).toBe(true)
    expect(isAutomationActor('github-actions[bot]')).toBe(true)
    expect(isAutomationActor('renovate[bot]')).toBe(true)
  })

  it('detects github-actions without [bot]', () => {
    expect(isAutomationActor('github-actions')).toBe(true)
  })

  it('detects app/github-actions', () => {
    expect(isAutomationActor('app/github-actions')).toBe(true)
  })

  it('returns false for human users', () => {
    expect(isAutomationActor('dsyme')).toBe(false)
    expect(isAutomationActor('octocat')).toBe(false)
  })

  it('returns false for empty string', () => {
    expect(isAutomationActor('')).toBe(false)
  })
})

describe('stripCodeFences', () => {
  it('strips markdown code fences', () => {
    expect(stripCodeFences('```markdown\n# Hello\n```')).toBe('# Hello')
  })

  it('strips generic code fences', () => {
    expect(stripCodeFences('```\nsome content\n```')).toBe('some content')
  })

  it('leaves unfenced text alone', () => {
    expect(stripCodeFences('# Hello world')).toBe('# Hello world')
  })

  it('handles whitespace around fences', () => {
    expect(stripCodeFences('  ```md\ncontent\n```  ')).toBe('content')
  })
})

describe('extractAutomationName', () => {
  it('extracts from "Generated by [Name](url)" pattern', () => {
    expect(extractAutomationName('Generated by [Repo Assist](https://example.com)')).toBe('Repo Assist')
  })

  it('extracts from gh-aw comment pattern', () => {
    expect(extractAutomationName('gh-aw-agentic-workflow: MyWorkflow, run 123')).toBe('MyWorkflow')
  })

  it('returns null for plain text', () => {
    expect(extractAutomationName('Just a regular comment')).toBeNull()
  })

  it('returns null for empty string', () => {
    expect(extractAutomationName('')).toBeNull()
  })
})

// === GhBridge class tests (with mocked execFile) ===

// Mock child_process.execFile with proper promisify support.
// Node's real execFile has [util.promisify.custom] which returns {stdout, stderr}.
// We need to replicate that so promisify(execFile) works correctly in the module.

const mockExecFileAsync = vi.hoisted(() => vi.fn<(cmd: string, args: string[], opts: unknown) => Promise<{ stdout: string; stderr: string }>>())

vi.mock('child_process', async () => {
  const util = await import('util')
  const execFile = Object.assign(
    vi.fn(),
    { [util.promisify.custom!]: mockExecFileAsync }
  )
  return { execFile }
})

describe('GhBridge', () => {
  let bridge: GhBridge

  beforeEach(() => {
    vi.clearAllMocks()
    bridge = new GhBridge()
  })

  describe('exec', () => {
    it('calls gh with parsed args and returns result', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: 'output', stderr: '' })

      const result = await bridge.exec('issue list -R owner/repo')
      expect(result.exitCode).toBe(0)
      expect(result.stdout).toBe('output')
      expect(mockExecFileAsync).toHaveBeenCalledWith(
        'gh',
        ['issue', 'list', '-R', 'owner/repo'],
        expect.objectContaining({ timeout: 30000 })
      )
    })

    it('handles exec errors gracefully', async () => {
      const err = Object.assign(new Error('command failed'), { code: 1, stderr: 'error output', stdout: '' })
      mockExecFileAsync.mockRejectedValue(err)

      const result = await bridge.exec('bad command')
      expect(result.exitCode).toBe(1)
      expect(result.stderr).toContain('error output')
    })
  })

  describe('getCommandLog', () => {
    it('starts empty', () => {
      expect(bridge.getCommandLog()).toEqual([])
    })

    it('records commands after exec', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '[]', stderr: '' })

      await bridge.exec('issue list -R owner/repo')
      const log = bridge.getCommandLog()
      expect(log.length).toBe(1)
      expect(log[0].command).toContain('issue')
      expect(log[0].exitCode).toBe(0)
    })
  })

  describe('dry-run behavior', () => {
    it('markPRReady returns dry-run result when writeMode is false', async () => {
      const result = await bridge.markPRReady('owner/repo', 1, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('updatePRBranch returns dry-run result when writeMode is false', async () => {
      const result = await bridge.updatePRBranch('owner/repo', 1, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('approvePR returns dry-run result when writeMode is false', async () => {
      const result = await bridge.approvePR('owner/repo', 1, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('closeIssue returns dry-run result when writeMode is false', async () => {
      const result = await bridge.closeIssue('owner/repo', 1, 'completed', false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('reopenIssue returns dry-run result when writeMode is false', async () => {
      const result = await bridge.reopenIssue('owner/repo', 1, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('addComment returns dry-run result when writeMode is false', async () => {
      const result = await bridge.addComment('owner/repo', 1, 'test comment', false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('addComment passes body as a separate arg to avoid quoting issues', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })
      await bridge.addComment('owner/repo', 1, 'body with "double quotes"', true)
      expect(mockExecFileAsync).toHaveBeenCalledWith(
        'gh',
        ['issue', 'comment', '1', '-R', 'owner/repo', '--body', 'body with "double quotes"'],
        expect.anything()
      )
    })

    it('mergePR returns dry-run result when writeMode is false', async () => {
      const result = await bridge.mergePR('owner/repo', 1, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('addLabel returns dry-run result when writeMode is false', async () => {
      const result = await bridge.addLabel('owner/repo', 42, 'issue', 'bug', false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('closePR returns dry-run result when writeMode is false', async () => {
      const result = await bridge.closePR('owner/repo', 1, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('cancelRun returns dry-run result when writeMode is false', async () => {
      const result = await bridge.cancelRun('owner/repo', 12345, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('removeLabel returns dry-run result when writeMode is false', async () => {
      const result = await bridge.removeLabel('owner/repo', 42, 'pr', 'enhancement', false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('rerunFailedJobs returns dry-run result when writeMode is false', async () => {
      const result = await bridge.rerunFailedJobs('owner/repo', 12345, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
    })

    it('requestReview returns dry-run result when writeMode is false', async () => {
      const result = await bridge.requestReview('owner/repo', 7, 'octocat', false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('enableWorkflow returns dry-run result when writeMode is false', async () => {
      const result = await bridge.enableWorkflow('owner/repo', 123, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('disableWorkflow returns dry-run result when writeMode is false', async () => {
      const result = await bridge.disableWorkflow('owner/repo', 123, false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })
  })

  describe('getIssues', () => {
    it('returns parsed JSON on success', async () => {
      const issues = [{ number: 1, title: 'Test' }]
      mockExecFileAsync.mockResolvedValue({ stdout: JSON.stringify(issues), stderr: '' })

      const result = await bridge.getIssues('owner/repo')
      expect(result).toEqual(issues)
    })

    it('returns empty array on exec failure', async () => {
      mockExecFileAsync.mockRejectedValue(Object.assign(new Error('fail'), { code: 1, stderr: 'err', stdout: '' }))

      const result = await bridge.getIssues('owner/repo')
      expect(result).toEqual([])
    })

    it('returns empty array on invalid JSON', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: 'not json', stderr: '' })

      const result = await bridge.getIssues('owner/repo')
      expect(result).toEqual([])
    })
  })

  describe('getRepoLabels', () => {
    it('returns parsed label array on success', async () => {
      const labels = [{ name: 'bug', color: 'd73a4a' }, { name: 'enhancement', color: 'a2eeef' }]
      mockExecFileAsync.mockResolvedValue({ stdout: JSON.stringify(labels), stderr: '' })

      const result = await bridge.getRepoLabels('owner/repo')
      expect(result).toEqual(labels)
    })

    it('returns empty array on failure', async () => {
      mockExecFileAsync.mockRejectedValue(Object.assign(new Error('fail'), { code: 1, stderr: 'err', stdout: '' }))

      const result = await bridge.getRepoLabels('owner/repo')
      expect(result).toEqual([])
    })
  })

  describe('getPRs', () => {
    it('returns parsed JSON on success', async () => {
      const prs = [{ number: 1, title: 'PR Test' }]
      mockExecFileAsync.mockResolvedValue({ stdout: JSON.stringify(prs), stderr: '' })

      const result = await bridge.getPRs('owner/repo')
      expect(result).toEqual(prs)
    })
  })

  describe('getRuns', () => {
    it('filters out cancelled and skipped runs', async () => {
      const runs = [
        { databaseId: 1, conclusion: 'success', status: 'completed' },
        { databaseId: 2, conclusion: 'cancelled', status: 'completed' },
        { databaseId: 3, conclusion: 'skipped', status: 'completed' },
        { databaseId: 4, conclusion: 'failure', status: 'completed' },
      ]
      mockExecFileAsync.mockResolvedValue({ stdout: JSON.stringify(runs), stderr: '' })

      const result = await bridge.getRuns('owner/repo')
      expect(result).toHaveLength(2)
      expect((result[0] as { databaseId: number }).databaseId).toBe(1)
      expect((result[1] as { databaseId: number }).databaseId).toBe(4)
    })
  })

  describe('getPRBranchStatus', () => {
    it('uses correct compare direction base...head', async () => {
      const calls: Array<{ cmd: string; args: string[] }> = []
      mockExecFileAsync.mockImplementation(async (cmd: string, args: string[]) => {
        calls.push({ cmd, args })
        // First call: pr view for refs
        if (args.some(a => a.includes('headRefName'))) {
          return { stdout: JSON.stringify({ headRefName: 'feature', baseRefName: 'main' }), stderr: '' }
        }
        // Second call: compare API
        return { stdout: '3', stderr: '' }
      })

      const result = await bridge.getPRBranchStatus('owner/repo', 1)
      // Verify the compare call uses base...head direction
      const compareCall = calls.find(c => c.args.some(a => a.includes('compare/')))
      expect(compareCall).toBeDefined()
      expect(compareCall!.args.join(' ')).toContain('compare/main...feature')
      expect(result.behindBy).toBe(3)
      expect(result.status).toBe('behind')
    })

    it('returns up_to_date when behindBy is 0', async () => {
      let callIndex = 0
      mockExecFileAsync.mockImplementation(async () => {
        callIndex++
        if (callIndex === 1) {
          return { stdout: JSON.stringify({ headRefName: 'feature', baseRefName: 'main' }), stderr: '' }
        }
        return { stdout: '0', stderr: '' }
      })

      const result = await bridge.getPRBranchStatus('owner/repo', 1)
      expect(result.status).toBe('up_to_date')
      expect(result.behindBy).toBe(0)
    })

    it('returns unknown on first exec failure', async () => {
      mockExecFileAsync.mockRejectedValue(Object.assign(new Error('fail'), { code: 1, stderr: 'err', stdout: '' }))

      const result = await bridge.getPRBranchStatus('owner/repo', 1)
      expect(result.status).toBe('unknown')
    })
  })

  describe('getConfiguredRepos', () => {
    it('returns repos from remote config', async () => {
      let callIndex = 0
      mockExecFileAsync.mockImplementation(async () => {
        callIndex++
        if (callIndex === 1) {
          // getUsername
          return { stdout: 'testuser\n', stderr: '' }
        }
        // getConfiguredRepos - returns base64 encoded config
        const config = JSON.stringify({ repositories: ['owner/repo1', 'owner/repo2'] })
        const encoded = Buffer.from(config).toString('base64')
        return { stdout: encoded, stderr: '' }
      })

      const repos = await bridge.getConfiguredRepos()
      expect(repos).toEqual(['owner/repo1', 'owner/repo2'])
    })

    it('returns empty array when username is unknown', async () => {
      mockExecFileAsync.mockRejectedValue(new Error('no auth'))

      const repos = await bridge.getConfiguredRepos()
      expect(repos).toEqual([])
    })
  })

  describe('scanPTAL', () => {
    it('returns items where last comment is from a bot', async () => {
      const issueData = {
        data: {
          repository: {
            issues: {
              nodes: [{
                number: 42,
                title: 'Bot issue',
                body: 'Generated by [Test Bot](https://example.com)',
                author: { login: 'human' },
                createdAt: '2024-01-01T00:00:00Z',
                updatedAt: '2024-01-02T00:00:00Z',
                comments: {
                  nodes: [{
                    id: 'IC_123',
                    author: { login: 'github-actions[bot]' },
                    body: 'Bot comment',
                    createdAt: '2024-01-02T00:00:00Z',
                  }]
                },
              }],
              pageInfo: { hasNextPage: false, endCursor: '' },
            },
          },
        },
      }
      const prData = {
        data: {
          repository: {
            pullRequests: {
              nodes: [],
              pageInfo: { hasNextPage: false, endCursor: '' },
            },
          },
        },
      }

      let callIndex = 0
      mockExecFileAsync.mockImplementation(async () => {
        callIndex++
        if (callIndex === 1) return { stdout: JSON.stringify(issueData), stderr: '' }
        return { stdout: JSON.stringify(prData), stderr: '' }
      })

      const items = await bridge.scanPTAL(['owner/repo'], {})
      expect(items.length).toBe(1)
      expect(items[0].number).toBe(42)
      expect(items[0].type).toBe('issue')
      expect(items[0].lastActivity.actor).toBe('github-actions[bot]')
    })

    it('skips items where last comment is from a human', async () => {
      const issueData = {
        data: {
          repository: {
            issues: {
              nodes: [{
                number: 42,
                title: 'Human issue',
                body: '',
                author: { login: 'human' },
                createdAt: '2024-01-01T00:00:00Z',
                updatedAt: '2024-01-02T00:00:00Z',
                comments: {
                  nodes: [{
                    id: 'IC_456',
                    author: { login: 'humandev' },
                    body: 'Human comment',
                    createdAt: '2024-01-02T00:00:00Z',
                  }]
                },
              }],
              pageInfo: { hasNextPage: false, endCursor: '' },
            },
          },
        },
      }
      const prData = {
        data: {
          repository: {
            pullRequests: {
              nodes: [],
              pageInfo: { hasNextPage: false, endCursor: '' },
            },
          },
        },
      }

      let callIndex = 0
      mockExecFileAsync.mockImplementation(async () => {
        callIndex++
        if (callIndex === 1) return { stdout: JSON.stringify(issueData), stderr: '' }
        return { stdout: JSON.stringify(prData), stderr: '' }
      })

      const items = await bridge.scanPTAL(['owner/repo'], {})
      expect(items.length).toBe(0)
    })

    it('respects cleared state', async () => {
      const issueData = {
        data: {
          repository: {
            issues: {
              nodes: [{
                number: 42,
                title: 'Bot issue',
                body: '',
                author: { login: 'human' },
                createdAt: '2024-01-01T00:00:00Z',
                updatedAt: '2024-01-02T00:00:00Z',
                comments: {
                  nodes: [{
                    id: 'IC_123',
                    author: { login: 'dependabot[bot]' },
                    body: 'Dependabot comment',
                    createdAt: '2024-01-02T00:00:00Z',
                  }]
                },
              }],
              pageInfo: { hasNextPage: false, endCursor: '' },
            },
          },
        },
      }
      const prData = {
        data: {
          repository: {
            pullRequests: {
              nodes: [],
              pageInfo: { hasNextPage: false, endCursor: '' },
            },
          },
        },
      }

      let callIndex = 0
      mockExecFileAsync.mockImplementation(async () => {
        callIndex++
        if (callIndex === 1) return { stdout: JSON.stringify(issueData), stderr: '' }
        return { stdout: JSON.stringify(prData), stderr: '' }
      })

      const items = await bridge.scanPTAL(['owner/repo'], { 'owner/repo#42': 'IC_123' })
      expect(items.length).toBe(0)
    })

    it('scans multiple repos in parallel and merges results sorted by date', async () => {
      const makeIssueData = (number: number, botDate: string) => ({
        data: {
          repository: {
            issues: {
              nodes: [{
                number,
                title: `Issue ${number}`,
                body: '',
                author: { login: 'human' },
                createdAt: '2024-01-01T00:00:00Z',
                updatedAt: botDate,
                comments: {
                  nodes: [{
                    id: `IC_${number}`,
                    author: { login: 'github-actions[bot]' },
                    body: 'Bot comment',
                    createdAt: botDate,
                  }]
                },
              }],
              pageInfo: { hasNextPage: false, endCursor: '' },
            },
          },
        },
      })
      const prData = { data: { repository: { pullRequests: { nodes: [], pageInfo: { hasNextPage: false, endCursor: '' } } } } }

      // Repo1 has a newer bot comment; repo2 has an older one
      const perRepoResponses: Record<string, [unknown, unknown]> = {
        'owner/repo1': [makeIssueData(10, '2024-01-03T00:00:00Z'), prData],
        'owner/repo2': [makeIssueData(20, '2024-01-02T00:00:00Z'), prData],
      }
      const callCount: Record<string, number> = {}
      mockExecFileAsync.mockImplementation(async (_cmd: string, args: string[]) => {
        // Identify which repo from the -F owner=... and name=... args
        const ownerArg = args.find((_: string, i: number) => i > 0 && args[i - 1] === '-F' && args[i].startsWith('owner='))
        const nameArg = args.find((_: string, i: number) => i > 0 && args[i - 1] === '-F' && args[i].startsWith('name='))
        const owner = ownerArg?.split('=')[1] ?? 'unknown'
        const name = nameArg?.split('=')[1] ?? 'unknown'
        const repoKey = `${owner}/${name}`
        callCount[repoKey] = (callCount[repoKey] ?? 0) + 1
        const responses = perRepoResponses[repoKey]
        const data = responses ? responses[(callCount[repoKey] - 1) % 2] : prData
        return { stdout: JSON.stringify(data), stderr: '' }
      })

      const items = await bridge.scanPTAL(['owner/repo1', 'owner/repo2'], {})
      expect(items.length).toBe(2)
      // Verify sorted newest-first
      expect(items[0].lastActivity.when >= items[1].lastActivity.when).toBe(true)
      // Verify both repos contributed
      const repos = items.map(i => i.repo)
      expect(repos).toContain('owner/repo1')
      expect(repos).toContain('owner/repo2')
    })
  })

  describe('enableWorkflow / disableWorkflow', () => {
    it('enableWorkflow returns dry-run result when writeMode is false', async () => {
      const result = await bridge.enableWorkflow('owner/repo', 42, false)
      expect(result.exitCode).toBe(0)
      expect(result.stdout).toContain('[DRY RUN]')
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('enableWorkflow calls gh when writeMode is true', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })
      const result = await bridge.enableWorkflow('owner/repo', 42, true)
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).toHaveBeenCalledWith(
        'gh',
        expect.arrayContaining(['workflow', 'enable', '42', '-R', 'owner/repo']),
        expect.any(Object)
      )
    })

    it('disableWorkflow returns dry-run result when writeMode is false', async () => {
      const result = await bridge.disableWorkflow('owner/repo', 7, false)
      expect(result.exitCode).toBe(0)
      expect(result.stdout).toContain('[DRY RUN]')
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('disableWorkflow calls gh when writeMode is true', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })
      const result = await bridge.disableWorkflow('owner/repo', 7, true)
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).toHaveBeenCalledWith(
        'gh',
        expect.arrayContaining(['workflow', 'disable', '7', '-R', 'owner/repo']),
        expect.any(Object)
      )
    })
  })

  describe('getFileContent', () => {
    it('decodes base64 file content on success', async () => {
      const content = 'Hello, world!'
      const encoded = Buffer.from(content).toString('base64')
      mockExecFileAsync.mockResolvedValue({ stdout: encoded + '\n', stderr: '' })

      const result = await bridge.getFileContent('owner/repo', 'README.md')
      expect(result).toBe(content)
    })

    it('returns null when exec fails', async () => {
      mockExecFileAsync.mockRejectedValue(Object.assign(new Error('not found'), { code: 1, stderr: 'Not Found', stdout: '' }))

      const result = await bridge.getFileContent('owner/repo', 'missing.txt')
      expect(result).toBeNull()
    })

    it('returns null when stdout is empty', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '   \n', stderr: '' })

      const result = await bridge.getFileContent('owner/repo', 'empty.txt')
      expect(result).toBeNull()
    })

    it('returns null for invalid base64', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '!!!not-base64!!!', stderr: '' })

      // Buffer.from with invalid base64 doesn't throw — it just produces garbled bytes —
      // so invalid base64 returns a (possibly empty/garbled) string, not null.
      // Verify the function doesn't throw at least.
      const result = await bridge.getFileContent('owner/repo', 'weird.txt')
      expect(typeof result === 'string' || result === null).toBe(true)
    })
  })

  describe('getWorkflows', () => {
    it('parses newline-separated JSON objects', async () => {
      const w1 = { id: 1, name: 'CI', path: '.github/workflows/ci.yml', state: 'active' }
      const w2 = { id: 2, name: 'Release', path: '.github/workflows/release.yml', state: 'active' }
      mockExecFileAsync.mockResolvedValue({
        stdout: JSON.stringify(w1) + '\n' + JSON.stringify(w2) + '\n',
        stderr: ''
      })

      const result = await bridge.getWorkflows('owner/repo')
      expect(result).toHaveLength(2)
      expect(result[0]).toMatchObject({ id: 1, name: 'CI' })
      expect(result[1]).toMatchObject({ id: 2, name: 'Release' })
    })

    it('returns empty array on exec failure', async () => {
      mockExecFileAsync.mockRejectedValue(Object.assign(new Error('fail'), { code: 1, stderr: 'err', stdout: '' }))

      const result = await bridge.getWorkflows('owner/repo')
      expect(result).toEqual([])
    })

    it('returns empty array on invalid JSON', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: 'not json at all', stderr: '' })

      const result = await bridge.getWorkflows('owner/repo')
      expect(result).toEqual([])
    })

    it('returns empty array when stdout is empty', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })

      const result = await bridge.getWorkflows('owner/repo')
      expect(result).toEqual([])
    })
  })

  describe('getPRTimeline', () => {
    it('parses newline-separated JSON objects and filters to relevant events', async () => {
      const e1 = { event: 'committed', created_at: '2024-01-01T00:00:00Z', sha: 'abc123' }
      const e2 = { event: 'commented', created_at: '2024-01-02T00:00:00Z', body: 'lgtm' }
      const e3 = { event: 'subscribed', created_at: '2024-01-02T00:00:00Z' }
      mockExecFileAsync.mockResolvedValue({
        stdout: [e1, e2, e3].map(e => JSON.stringify(e)).join('\n') + '\n',
        stderr: ''
      })

      const result = await bridge.getPRTimeline('owner/repo', 1)
      expect(result).toHaveLength(2)
      expect(result[0]).toMatchObject({ event: 'committed', sha: 'abc123' })
      expect(result[1]).toMatchObject({ event: 'commented', body: 'lgtm' })
    })

    it('handles multi-page output (newline-separated objects across pages)', async () => {
      // Simulate --paginate --jq '.[]': each event is a separate JSON line
      const events = [
        { event: 'committed', created_at: '2024-01-01T00:00:00Z' },
        { event: 'reviewed', created_at: '2024-01-02T00:00:00Z' },
        { event: 'merged', created_at: '2024-01-03T00:00:00Z' },
      ]
      mockExecFileAsync.mockResolvedValue({
        stdout: events.map(e => JSON.stringify(e)).join('\n'),
        stderr: ''
      })

      const result = await bridge.getPRTimeline('owner/repo', 42)
      expect(result).toHaveLength(3)
      expect(result.map(e => e.event)).toEqual(['committed', 'reviewed', 'merged'])
    })

    it('returns empty array on exec failure', async () => {
      mockExecFileAsync.mockRejectedValue(Object.assign(new Error('fail'), { code: 1, stderr: 'err', stdout: '' }))

      const result = await bridge.getPRTimeline('owner/repo', 1)
      expect(result).toEqual([])
    })

    it('returns empty array when stdout is empty', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })

      const result = await bridge.getPRTimeline('owner/repo', 1)
      expect(result).toEqual([])
    })

    it('uses --paginate --jq .[] in the command', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })
      await bridge.getPRTimeline('owner/repo', 5)
      const call = mockExecFileAsync.mock.calls[0]
      const args: string[] = call[1] as string[]
      expect(args.join(' ')).toContain('--paginate')
      expect(args).toContain('--jq')
      expect(args).toContain('.[]')
    })
  })

  describe('requestReview', () => {
    it('returns dry-run result when writeMode is false', async () => {
      const result = await bridge.requestReview('owner/repo', 7, 'octocat', false)
      expect(result.stdout).toContain('DRY RUN')
      expect(result.exitCode).toBe(0)
      expect(mockExecFileAsync).not.toHaveBeenCalled()
    })

    it('calls gh pr edit --add-reviewer when writeMode is true', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })

      await bridge.requestReview('owner/repo', 7, 'octocat', true)
      const call = mockExecFileAsync.mock.calls[0]
      const args: string[] = call[1] as string[]
      expect(args).toContain('edit')
      expect(args).toContain('7')
      expect(args).toContain('--add-reviewer')
      expect(args).toContain('octocat')
    })

    it('includes repo flag in command', async () => {
      mockExecFileAsync.mockResolvedValue({ stdout: '', stderr: '' })

      await bridge.requestReview('owner/repo', 3, 'reviewer1', true)
      const call = mockExecFileAsync.mock.calls[0]
      const args: string[] = call[1] as string[]
      expect(args).toContain('-R')
      expect(args).toContain('owner/repo')
    })
  })
})
